/-!
# Logos Closure Principle

This file formalizes the binding-layer idea:

The ROOT properties should not be treated only as a flat list. A stronger model
represents some properties as a closure system generated by a rational-structural
kernel.

This is a finite formal pilot. It does not prove that the theological
interpretation is true.
-/

namespace Theophysics
namespace NumbersInGod
namespace LogosClosure

inductive RootProperty where
  | truth
  | consistency
  | rationality
  | order
  | intelligibility
  | law
  | invariance
  | objectivity
  | generativity
  | judging
  | necessity
  | foundationality
  | unity
  | immateriality
  | simplicity
  | infinity
  | perfection
deriving Repr, DecidableEq

def kernel : List RootProperty := [
  .truth,
  .consistency,
  .rationality,
  .order,
  .intelligibility
]

def companionsOf : RootProperty -> List RootProperty
  | .truth => [.objectivity, .judging]
  | .consistency => [.rationality, .law]
  | .rationality => [.intelligibility, .order]
  | .order => [.law, .generativity, .unity]
  | .intelligibility => [.truth, .objectivity]
  | .law => [.invariance, .necessity]
  | .invariance => [.objectivity]
  | .objectivity => []
  | .generativity => [.order]
  | .judging => [.truth, .law]
  | .necessity => [.invariance]
  | .foundationality => [.necessity]
  | .unity => [.consistency]
  | .immateriality => []
  | .simplicity => []
  | .infinity => []
  | .perfection => [.truth, .consistency]

def oneStepClosure (profile : RootProperty -> Bool) : RootProperty -> Bool :=
  fun q =>
    profile q ||
    kernel.any (fun p => profile p && (companionsOf p).contains q) ||
    (List.any [
      .truth, .consistency, .rationality, .order, .intelligibility,
      .law, .invariance, .objectivity, .generativity, .judging,
      .necessity, .foundationality, .unity, .immateriality,
      .simplicity, .infinity, .perfection
    ] (fun p => profile p && (companionsOf p).contains q))

def fullKernelProfile : RootProperty -> Bool :=
  fun p => kernel.contains p

def closedFromKernel : RootProperty -> Bool :=
  oneStepClosure (oneStepClosure (oneStepClosure fullKernelProfile))

def IsClosed (profile : RootProperty -> Bool) : Prop :=
  forall p q : RootProperty,
    profile p = true ->
    (companionsOf p).contains q = true ->
    profile q = true

theorem kernel_count :
    kernel.length = 5 := by
  native_decide

theorem consistency_requires_rationality :
    (companionsOf RootProperty.consistency).contains
      RootProperty.rationality = true := by
  native_decide

theorem intelligibility_requires_truth :
    (companionsOf RootProperty.intelligibility).contains
      RootProperty.truth = true := by
  native_decide

theorem generativity_requires_order :
    (companionsOf RootProperty.generativity).contains
      RootProperty.order = true := by
  native_decide

theorem law_requires_invariance :
    (companionsOf RootProperty.law).contains
      RootProperty.invariance = true := by
  native_decide

theorem kernel_generates_law :
    closedFromKernel RootProperty.law = true := by
  native_decide

theorem kernel_generates_invariance :
    closedFromKernel RootProperty.invariance = true := by
  native_decide

theorem kernel_generates_objectivity :
    closedFromKernel RootProperty.objectivity = true := by
  native_decide

theorem kernel_generates_generativity :
    closedFromKernel RootProperty.generativity = true := by
  native_decide

theorem kernel_generates_judging :
    closedFromKernel RootProperty.judging = true := by
  native_decide

/-!
Bridge-risk properties are intentionally not generated by this first closure
kernel. They require separate semantic/theological arguments.
-/

theorem kernel_does_not_generate_immateriality :
    closedFromKernel RootProperty.immateriality = false := by
  native_decide

theorem kernel_does_not_generate_simplicity :
    closedFromKernel RootProperty.simplicity = false := by
  native_decide

theorem kernel_does_not_generate_infinity :
    closedFromKernel RootProperty.infinity = false := by
  native_decide

/-! ## Negative controls -/

def flatAllTrue : RootProperty -> Bool := fun _ => true

theorem flat_all_true_is_closed_but_uninformative :
    IsClosed flatAllTrue := by
  intro p q _ _
  rfl

def missingTruthProfile : RootProperty -> Bool
  | .truth => false
  | _ => true

theorem missing_truth_profile_not_closed :
    Not (IsClosed missingTruthProfile) := by
  intro h
  have hIntel : missingTruthProfile RootProperty.intelligibility = true := rfl
  have hNeeds :
      (companionsOf RootProperty.intelligibility).contains
        RootProperty.truth = true := by
    native_decide
  have hTruth := h RootProperty.intelligibility RootProperty.truth hIntel hNeeds
  contradiction

def missingOrderProfile : RootProperty -> Bool
  | .order => false
  | _ => true

theorem missing_order_profile_not_closed :
    Not (IsClosed missingOrderProfile) := by
  intro h
  have hGen : missingOrderProfile RootProperty.generativity = true := rfl
  have hNeeds :
      (companionsOf RootProperty.generativity).contains
        RootProperty.order = true := by
    native_decide
  have hOrder := h RootProperty.generativity RootProperty.order hGen hNeeds
  contradiction

/-! ## Composition-style reading

The closure principle gives a way to talk about the binding layer:
properties co-occur because companion rules force closure under the kernel.
-/

structure LogosClosedProfile where
  has : RootProperty -> Bool
  closed : IsClosed has

def flatClosedProfile : LogosClosedProfile where
  has := flatAllTrue
  closed := flat_all_true_is_closed_but_uninformative

theorem closed_profile_preserves_companions
    (profile : LogosClosedProfile)
    (p q : RootProperty)
    (hp : profile.has p = true)
    (hcompanion : (companionsOf p).contains q = true) :
    profile.has q = true :=
  profile.closed p q hp hcompanion

end LogosClosure
end NumbersInGod
end Theophysics
